name: Continuous Integration and Delivery

on: [push]

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/phicite-api

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${{ vars.HEROKU_APP_NAME }}/phicite-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
      - name: Pull images
        run: |
          docker pull ${{ env.IMAGE }}-builder:latest || true
          docker pull ${{ env.IMAGE }}-final:latest || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from ${{ env.IMAGE }}-builder:latest \
            --tag ${{ env.IMAGE }}-builder:latest \
            --file ./phicite/Dockerfile.prod \
            "./phicite"
          docker build \
            --target final \
            --cache-from ${{ env.IMAGE }}-final:latest \
            --tag ${{ env.IMAGE }}-final:latest \
            --file ./phicite/Dockerfile.prod \
            "./phicite"
          docker build \
            --target tester \
            --cache-from ${{ env.IMAGE }}-tester:latest \
            --tag ${{ env.IMAGE }}-tester:latest \
            --file ./phicite/Dockerfile.prod \
            "./phicite"
      - name: Push images
        run: |
          docker push ${{ env.IMAGE }}-builder:latest
          docker push ${{ env.IMAGE }}-final:latest
          docker push ${{ env.IMAGE }}-tester:latest

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GHCR_PAT }} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
      - name: Pull builder image
        run: |
          docker pull ${{ env.IMAGE }}-tester:latest
      - name: Run tests and checks in tester image
        run: |
          docker run \
            --name fastapi-tdd \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e JWT_SECRET_KEY=d8caaa7f91ce694f1ec0003f7a1db97a7b09f139c2d899487a336833c23a147f \
            -e JWT_ALGORITHM=HS256 \
            -e ACCESS_TOKEN_EXPIRE_MINUTES=15 \
            -e BASE_URL=http://localhost:8004 \
            -e DATABASE_URL=sqlite://sqlite.db \
            -e DATABASE_TEST_URL=sqlite://sqlite.db \
            -p 5003:8765 \
            ${{ env.IMAGE }}-tester:latest \
            sh -c "pwd && ls -l . && find . -name 'test_*.py' && python -m pytest -v . && python -m ruff check ."

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/${{ vars.HEROKU_APP_NAME }}/phicite-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GHCR_PAT }} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
      - name: Pull final image
        run: |
          docker pull ${{ env.IMAGE }}-final:latest
      - name: Log in to the Heroku Container Registry
        run: docker login -u _ -p ${HEROKU_AUTH_TOKEN} registry.heroku.com
        env:
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - name: Tag image for Heroku
        run: |
          docker tag ${{ env.IMAGE }}-final:latest ${{ env.HEROKU_REGISTRY_IMAGE }}
      - name: Push to the registry
        run: docker push ${{ env.HEROKU_REGISTRY_IMAGE }}
      - name: Set environment variables
        run: |
          echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
          echo "HEROKU_AUTH_TOKEN=${{ secrets.HEROKU_AUTH_TOKEN }}" >> $GITHUB_ENV
      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh